"""
core/output_manager.py — Document & YAML output: Skills 8, 10, 11a, 11b.

All functions are plain — no @mcp.tool() decorators. Registration happens in server.py.
"""

import os
import re
from datetime import datetime

from azure.devops.v7_1.work_item_tracking.models import Wiql
from docx import Document as DocxDocument
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

from core.utils import (
    get_azure_client,
    handle_error,
    is_arabic,
    sanitize_wiql_string,
    infer_tc_attributes_from_title,
    parse_steps_xml,
    apply_rtl,
    set_cell_shading,
    merge_cells_in_row,
)


# ─────────────────────────────────────────────────────────────────────────────
# SKILL 8: SMART YAML AUTOMATION
# ─────────────────────────────────────────────────────────────────────────────

def generate_playwright_yaml(parent_id: int) -> dict:
    """
    SKILL 8: Smart YAML Automation

    Generates Playwright-ready YAML for all Automated TCs under a PBI.
    Manual TCs are excluded to prevent framework contamination.

    Args:
        parent_id (int): The PBI/User Story work item ID

    Returns:
        {parent_id, parent_title, test_cases_count, automated_count,
         manual_skipped, yaml_content}
    """
    try:
        client = get_azure_client()

        parent = client.get_work_item(parent_id, expand="Relations")
        parent_title = parent.fields.get('System.Title', '')

        if not parent.relations:
            return {"error": "No test cases linked to this PBI."}

        tc_ids = [
            int(rel.url.split("/")[-1])
            for rel in parent.relations
            if rel.rel == "System.LinkTypes.Hierarchy-Forward"
        ]

        if not tc_ids:
            return {"error": "No child test cases found."}

        work_items = client.get_work_items(ids=tc_ids, expand="All")

        yaml_lines = [
            "# Auto-generated Playwright test suite",
            f"# Source PBI: {parent_id} - {parent_title}",
            "# Generated by: QA-Final-V4 MCP Server",
            "# Note: Only 'Automated' test cases included",
            "",
            "suite:",
            f'  name: "PBI-{parent_id}"',
            f'  description: "{parent_title}"',
            "  tests:"
        ]

        automated_count = manual_count = total_count = 0

        for item in work_items:
            if item.fields.get('System.WorkItemType') != 'Test Case':
                continue

            total_count += 1
            tc_title = item.fields.get('System.Title', '')
            tags = item.fields.get('System.Tags', '')
            tag_list = [t.strip() for t in tags.split(';')] if tags else []

            if "Manual" in tag_list:
                manual_count += 1
                continue

            automated_count += 1

            test_type = next((t.lower() for t in tag_list if t in ["UI", "Functional", "Edge", "Intensive"]), "functional")
            scenario = next((t for t in tag_list if t in ["positive", "negative"]), "positive")
            impact_area = next((t for t in tag_list if t in ["UI", "Backend", "Both"]), "UI")

            steps_raw = parse_steps_xml(item.fields.get('Microsoft.VSTS.TCM.Steps', ''))
            steps = [s["action"] for s in steps_raw]
            expected = [s["expected"] for s in steps_raw]

            yaml_lines += [
                "",
                f'    - id: "TC-{item.id}"',
                f'      title: "{tc_title}"',
                f'      type: "{test_type}"',
                f'      scenario: "{scenario}"',
                f'      impact_area: "{impact_area}"',
                f'      execution_type: "Automated"',
                f'      tags: {tag_list}',
                "      steps:"
            ]

            for j, (s, e) in enumerate(zip(steps, expected), 1):
                yaml_lines += [
                    f'        - step: {j}',
                    f'          action: "{s}"',
                    f'          expected: "{e}"'
                ]

        return {
            "parent_id": parent_id,
            "parent_title": parent_title,
            "test_cases_count": total_count,
            "automated_count": automated_count,
            "manual_skipped": manual_count,
            "yaml_content": "\n".join(yaml_lines)
        }

    except Exception as e:
        return handle_error(e, "generate_playwright_yaml")


# ─────────────────────────────────────────────────────────────────────────────
# SKILL 10: CLIENT-READY UAT GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def _add_arabic_tc_table(doc, tc: dict):
    """3-column RTL table for Arabic TCs: Expected | Action | Step."""
    num_steps = len(tc['steps'])
    tbl = doc.add_table(rows=2 + max(num_steps, 1), cols=3, style="Table Grid")
    merge_cells_in_row(tbl, 0, 0, 2)

    title_cell = tbl.cell(0, 0)
    title_cell.text = tc['title']
    set_cell_shading(title_cell, "FDE9D9")
    for p in title_cell.paragraphs:
        for r in p.runs:
            r.font.bold = True
            r.font.size = Pt(12)
            r.font.color.rgb = RGBColor(0x1F, 0x38, 0x64)
        apply_rtl(p)

    for j, h in enumerate(["النتيجة المتوقعة", "الإجراء", "الخطوة"]):
        cell = tbl.cell(1, j)
        cell.text = h
        set_cell_shading(cell, "D9D9D9")
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.bold = True
            apply_rtl(p)

    if tc['steps']:
        for s_idx, step in enumerate(tc['steps']):
            tbl.cell(2 + s_idx, 0).text = step['expected']
            tbl.cell(2 + s_idx, 1).text = step['action']
            tbl.cell(2 + s_idx, 2).text = str(s_idx + 1)
            for j in range(3):
                for p in tbl.cell(2 + s_idx, j).paragraphs:
                    apply_rtl(p)
    else:
        tbl.cell(2, 2).text = "1"

    doc.add_paragraph("")


def _add_english_tc_table(doc, tc: dict, ac_text: str):
    """4-column LTR table for English TCs with prerequisites row."""
    ac_clean = re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', ac_text)).strip()
    num_steps = len(tc['steps'])
    tbl = doc.add_table(rows=3 + max(num_steps, 1), cols=4, style="Table Grid")

    merge_cells_in_row(tbl, 0, 0, 3)
    title_cell = tbl.cell(0, 0)
    title_cell.text = f"TC : {tc['title']}"
    set_cell_shading(title_cell, "D9E2F3")
    for p in title_cell.paragraphs:
        for r in p.runs:
            r.font.bold = True
            r.font.size = Pt(10)

    merge_cells_in_row(tbl, 1, 0, 3)
    prereq_cell = tbl.cell(1, 0)
    prereq_cell.text = f"Prerequisites: {ac_clean[:200]}"
    for p in prereq_cell.paragraphs:
        for r in p.runs:
            r.font.size = Pt(9)
            r.font.italic = True

    for j, h in enumerate(["Step", "Action", "Expected System Response", "Feedback"]):
        cell = tbl.cell(2, j)
        cell.text = h
        set_cell_shading(cell, "E2EFDA")
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.bold = True
                r.font.size = Pt(9)

    if tc['steps']:
        for s_idx, step in enumerate(tc['steps']):
            tbl.cell(3 + s_idx, 0).text = str(s_idx + 1)
            tbl.cell(3 + s_idx, 1).text = step['action']
            tbl.cell(3 + s_idx, 2).text = step['expected']
            tbl.cell(3 + s_idx, 3).text = ""
            for j in range(4):
                for p in tbl.cell(3 + s_idx, j).paragraphs:
                    for r in p.runs:
                        r.font.size = Pt(9)
    else:
        tbl.cell(3, 0).text = "1"

    doc.add_paragraph("")


def generate_uat_document(
    iteration_path: str,
    project_name: str = "",
    output_path: str = "",
    include_all: bool = False
) -> dict:
    """
    SKILL 10: Client-Ready UAT Generation

    Generates a professional UAT (.docx) from a sprint, auto-detecting language
    per PBI. English PBIs use 4-column LTR tables with a cover page and changelog.
    Arabic PBIs use 3-column RTL tables.

    TC Filter (default): Only Functional + Positive test cases (stakeholder UAT scope).
    Set include_all=True to include Edge, Negative, and Intensive cases.

    Args:
        iteration_path (str): Sprint path
        project_name (str): Optional project name for cover page
        output_path (str): Optional output file path
        include_all (bool): Include all TC types (default: False)

    Returns:
        {status, file_path, language, total_pbis, total_test_cases, pbi_summary}
    """
    try:
        client = get_azure_client()
        project = os.getenv("AZURE_PROJECT")
        if not project_name:
            project_name = project
        safe_iter = sanitize_wiql_string(iteration_path)
        safe_proj = sanitize_wiql_string(project)

        query = f"""
            SELECT [System.Id], [System.Title], [Microsoft.VSTS.Common.AcceptanceCriteria]
            FROM WorkItems
            WHERE [System.WorkItemType] = 'Product Backlog Item'
              AND [System.IterationPath] = '{safe_iter}'
              AND [System.TeamProject] = '{safe_proj}'
            ORDER BY [System.Id] ASC
        """
        result = client.query_by_wiql(Wiql(query=query))

        if not result.work_items:
            return {"error": "No PBIs found in this sprint.", "iteration_path": iteration_path}

        pbi_ids = [item.id for item in result.work_items]
        pbi_items = client.get_work_items(ids=pbi_ids, expand="All")

        all_pbi_data = []
        ar_count = en_count = 0

        for pbi in pbi_items:
            pbi_title = pbi.fields.get('System.Title', '')
            pbi_ac = pbi.fields.get('Microsoft.VSTS.Common.AcceptanceCriteria', 'No AC')
            pbi_lang = "ar" if (is_arabic(pbi_title) or is_arabic(pbi_ac)) else "en"

            if pbi_lang == "ar":
                ar_count += 1
            else:
                en_count += 1

            tc_ids = [
                int(rel.url.split("/")[-1])
                for rel in (pbi.relations or [])
                if rel.rel == "System.LinkTypes.Hierarchy-Forward"
            ]

            test_cases = []
            if tc_ids:
                tc_items = client.get_work_items(ids=tc_ids, expand="All")
                for tc in tc_items:
                    if tc.fields.get('System.WorkItemType') != 'Test Case':
                        continue

                    tc_title = tc.fields.get('System.Title', '')
                    tc_tags = tc.fields.get('System.Tags', '')
                    tag_list = [t.strip() for t in tc_tags.split(';')] if tc_tags else []

                    if not include_all:
                        has_tags = any(t in tag_list for t in ["UI", "Functional", "Edge", "Intensive", "positive", "negative"])
                        tc_type = next((t for t in tag_list if t in ["UI", "Functional", "Edge", "Intensive"]), None) if has_tags else None
                        tc_scenario = next((t for t in tag_list if t in ["positive", "negative"]), None) if has_tags else None

                        if not has_tags:
                            inferred = infer_tc_attributes_from_title(tc_title)
                            tc_type = inferred["test_type"]
                            tc_scenario = inferred["scenario"]

                        if tc_type != "Functional" or tc_scenario != "positive":
                            continue

                    test_cases.append({
                        "id": tc.id,
                        "title": tc_title,
                        "priority": tc.fields.get('Microsoft.VSTS.Common.Priority', 2),
                        "steps": parse_steps_xml(tc.fields.get('Microsoft.VSTS.TCM.Steps', ''))
                    })

            all_pbi_data.append({
                "id": pbi.id,
                "title": pbi_title,
                "ac": pbi_ac,
                "language": pbi_lang,
                "test_cases": test_cases
            })

        majority_is_ar = ar_count >= en_count
        doc = DocxDocument()
        today = datetime.now().strftime("%Y-%m-%d")
        today_full = datetime.now().strftime("%b %dth, %Y")
        sprint_label = iteration_path.split("\\")[-1] if "\\" in iteration_path else iteration_path
        total_tcs = 0

        # Document header
        if majority_is_ar:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(f"حالات الاختبار - {project_name}")
            run.bold = True
            run.font.size = Pt(16)
            apply_rtl(p)
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(f"{project_name} — {sprint_label} Test Cases")
            run.font.size = Pt(12)
            apply_rtl(p)
            doc.add_paragraph("")
            doc.add_page_break()
            p = doc.add_heading("نطاق العمل (عناصر قائمة المنتج)", level=1)
            apply_rtl(p)
            for p_data in all_pbi_data:
                if p_data['test_cases']:
                    p = doc.add_paragraph(f"• PBI {p_data['id']}: {p_data['title']}")
                    apply_rtl(p)
            doc.add_page_break()
            p = doc.add_heading("حالات الاختبار (Test Cases)", level=1)
            apply_rtl(p)
        else:
            doc.add_paragraph("")
            doc.add_paragraph("")
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run("Prepared For")
            run.font.size = Pt(14)
            run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
            doc.add_paragraph("")
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(project_name)
            run.bold = True
            run.font.size = Pt(28)
            run.font.color.rgb = RGBColor(0x2E, 0x50, 0x90)
            doc.add_paragraph("")
            doc.add_paragraph("")
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run("By")
            run.font.size = Pt(14)
            run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
            doc.add_paragraph("")
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run("AI-Assisted QA (Claude)")
            run.bold = True
            run.font.size = Pt(16)
            doc.add_paragraph("")
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(today_full)
            run.font.size = Pt(14)
            doc.add_page_break()
            doc.add_heading("Document change Log", level=1)
            log_table = doc.add_table(rows=2, cols=4)
            for j, h in enumerate(["Date", "Changed By", "Reason Of Change", "Description of Change"]):
                cell = log_table.cell(0, j)
                cell.text = h
                set_cell_shading(cell, "D5E8F0")
                for p in cell.paragraphs:
                    for r in p.runs:
                        r.font.bold = True
                        r.font.size = Pt(10)
            log_table.cell(1, 0).text = today
            log_table.cell(1, 1).text = "AI-Assisted QA (Claude)"
            log_table.cell(1, 2).text = "Document Creation"
            log_table.cell(1, 3).text = ""
            doc.add_paragraph("")
            doc.add_heading("Introduction", level=1)
            doc.add_paragraph(f"This document represents {project_name} acceptance Checklist for {project_name} Site, and all its functional specifications.")
            doc.add_heading("Pre-Requisite Checklist(s)", level=1)
            doc.add_paragraph("It's recommended that the user is already acquainted with the system.")
            doc.add_page_break()
            doc.add_heading("Scope of Work (Product Backlog Items)", level=1)
            for p_data in all_pbi_data:
                if p_data['test_cases']:
                    doc.add_paragraph(f"• PBI {p_data['id']}: {p_data['title']}", style='List Bullet')
            doc.add_page_break()
            doc.add_heading("Test Cases", level=1)

        # Per-PBI sections
        for pbi_data in all_pbi_data:
            if not pbi_data['test_cases']:
                continue

            pbi_is_ar = pbi_data['language'] == "ar"
            p = doc.add_paragraph()
            run = p.add_run(pbi_data['title'])
            run.bold = True
            run.font.size = Pt(12)
            run.font.color.rgb = RGBColor(0x2E, 0x50, 0x90)
            if pbi_is_ar:
                apply_rtl(p)

            for tc in pbi_data['test_cases']:
                total_tcs += 1
                if pbi_is_ar:
                    _add_arabic_tc_table(doc, tc)
                else:
                    _add_english_tc_table(doc, tc, pbi_data['ac'])

        if not output_path:
            safe_name = project_name.replace(" ", "_")
            safe_sprint = sprint_label.replace(" ", "_")
            output_path = f"UAT_Document_{safe_name}_{safe_sprint}_{datetime.now().strftime('%Y-%m-%d')}.docx"

        doc.save(output_path)
        return {
            "status": "success",
            "file_path": os.path.abspath(output_path),
            "language": "ar" if majority_is_ar else "en",
            "total_pbis": len(all_pbi_data),
            "total_test_cases": total_tcs,
            "iteration_path": iteration_path,
            "pbi_summary": [
                {"id": p["id"], "title": p["title"], "test_cases_count": len(p["test_cases"])}
                for p in all_pbi_data
            ]
        }

    except Exception as e:
        return handle_error(e, "generate_uat_document")


# ─────────────────────────────────────────────────────────────────────────────
# SKILL 11a: UAT DOCUMENT REVIEW
# ─────────────────────────────────────────────────────────────────────────────

def review_uat_document(uat_file_path: str) -> dict:
    """
    SKILL 11a: UAT Review & Analysis

    Parses an existing UAT .docx and extracts structured content for QA review.

    Args:
        uat_file_path (str): Path to UAT .docx file

    Returns:
        {status, file_path, language, total_sections, sections, review_instructions}
    """
    try:
        if not os.path.exists(uat_file_path):
            return {"error": f"File not found: {uat_file_path}"}

        doc = DocxDocument(uat_file_path)
        sections = []
        current_section = {"heading": "Document Start", "content": [], "tables": []}

        for element in doc.element.body:
            tag = element.tag.split('}')[-1] if '}' in element.tag else element.tag
            if tag == 'p':
                pPr = element.find(qn('w:pPr'))
                if pPr is not None:
                    pStyle = pPr.find(qn('w:pStyle'))
                    if pStyle is not None and 'Heading' in pStyle.get(qn('w:val'), ''):
                        if current_section["content"] or current_section["tables"]:
                            sections.append(current_section)
                        text = ''.join(node.text or '' for node in element.iter(qn('w:t')))
                        current_section = {"heading": text, "content": [], "tables": []}
                        continue
                text = ''.join(node.text or '' for node in element.iter(qn('w:t')))
                if text.strip():
                    current_section["content"].append(text.strip())
            elif tag == 'tbl':
                table_data = [
                    [''.join(node.text or '' for node in cell.iter(qn('w:t'))).strip()
                     for cell in row.findall(qn('w:tc'))]
                    for row in element.findall(qn('w:tr'))
                ]
                current_section["tables"].append(table_data)

        if current_section["content"] or current_section["tables"]:
            sections.append(current_section)

        all_text = " ".join(" ".join(s["content"]) for s in sections)
        detected_lang = "ar" if is_arabic(all_text) else "en"

        return {
            "status": "parsed",
            "file_path": uat_file_path,
            "language": detected_lang,
            "total_sections": len(sections),
            "sections": sections,
            "review_instructions": "As QA Manager, review this UAT document for completeness, quality, and gaps."
        }

    except Exception as e:
        return handle_error(e, "review_uat_document")


# ─────────────────────────────────────────────────────────────────────────────
# SKILL 11b: UAT DOCUMENT REVISION
# ─────────────────────────────────────────────────────────────────────────────

def create_revised_uat_document(
    original_uat_path: str,
    review_comments: list,
    additional_test_cases: list = None,
    output_path: str = ""
) -> dict:
    """
    SKILL 11b: UAT Polishing & Revision

    Applies QA Manager review comments and appends missing test cases
    to an existing UAT document. Adds a bilingual review notes section.

    Each item in additional_test_cases: {title, steps: [{action, expected}], language?: "ar"|"en"}
    Language detection per TC mirrors Skills 3/4/10 — uses "language" field or auto-detects from title.

    Args:
        original_uat_path (str): Path to original UAT .docx
        review_comments (list[str]): QA Manager feedback lines
        additional_test_cases (list[dict]): New TCs to append
        output_path (str): Output path (defaults to original_Reviewed.docx)

    Returns:
        {status, file_path, language, review_comments_count, additional_test_cases_added}
    """
    if additional_test_cases is None:
        additional_test_cases = []

    try:
        if not os.path.exists(original_uat_path):
            return {"error": f"File not found: {original_uat_path}"}

        doc = DocxDocument(original_uat_path)
        all_text = "\n".join(p.text for p in doc.paragraphs if p.text)
        doc_is_ar = is_arabic(all_text)
        today = datetime.now().strftime("%Y-%m-%d")
        added_tc_count = 0

        for tc_data in additional_test_cases:
            tc_title = tc_data.get('title', '')
            tc_steps = tc_data.get('steps', [])
            tc_lang = tc_data.get('language', 'ar' if is_arabic(tc_title) else 'en')

            tc_dict = {"title": tc_title, "steps": tc_steps}

            if tc_lang == "ar":
                _add_arabic_tc_table(doc, tc_dict)
            else:
                _add_english_tc_table(doc, tc_dict, "")

            added_tc_count += 1
            doc.add_paragraph("")

        doc.add_page_break()
        review_title = "ملاحظات المراجعة" if doc_is_ar else "Review Notes"
        doc.add_heading(review_title, level=1)
        doc.add_paragraph(f"{'تمت المراجعة بواسطة' if doc_is_ar else 'Reviewed by'}: QA Manager (AI-Assisted Review)")
        doc.add_paragraph(f"{'تاريخ المراجعة' if doc_is_ar else 'Review Date'}: {today}")
        doc.add_heading("التغييرات المطبقة" if doc_is_ar else "Changes Applied", level=2)
        for i, comment in enumerate(review_comments, 1):
            doc.add_paragraph(f"{i}. {comment}")

        if not output_path:
            base, ext = os.path.splitext(original_uat_path)
            output_path = f"{base}_Reviewed{ext}"

        doc.save(output_path)
        return {
            "status": "success",
            "file_path": os.path.abspath(output_path),
            "language": "ar" if doc_is_ar else "en",
            "review_comments_count": len(review_comments),
            "additional_test_cases_added": added_tc_count
        }

    except Exception as e:
        return handle_error(e, "create_revised_uat_document")
